name:                TheJoyOfHaskell
version:             0.1.0.0
github:              "khajavi/TheJoyOfHaskell"
license:             BSD3
author:              "Milad Khajavi"
maintainer:          "khajavi@gmail.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/TheJoyOfHaskell#readme>

dependencies:
- base
- aeson
- bytestring

library:
  source-dirs: src

executables:
  TheJoyOfHaskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TheJoyOfHaskell

  typeclass:
    main:                Main.hs
    source-dirs:         app/typeclass
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - TheJoyOfHaskell

tests:
  TheJoyOfHaskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TheJoyOfHaskell
